*** Settings ***
Resource    ${CURDIR}/../page_locator/home_locator.resource
Resource    ${CURDIR}/../page_locator/file_upload_locator.resource
Resource    ${CURDIR}/../page_locator/multiple_windows_locator.resource
Resource    ${CURDIR}/../page_locator/sortable_data_tables_locator.resource
Resource    ${CURDIR}/../page_locator/add_remove_element_locator.resource
Resource    ${CURDIR}/../page_locator/checkboxes_locator.resource